BEGIN;

insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (1, 'Taxi zum Klo', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', '£5.73', 'Cabbage Roll', 1);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (2, 'Lupin III: First Contact (Rupan Sansei: Faasuto Kontakuto)', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '£23.65', 'Passion Fruit', 2);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (3, 'Who Is Cletis Tout?', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', '£31.01', 'Bread - Pumpernickel', 3);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (4, 'Fellini''s Roma (Roma)', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '£29.00', 'Squash - Guords', 4);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (5, 'Justice League: The Flashpoint Paradox', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', '£16.82', 'Sole - Iqf', 5);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (6, 'Best Seller', 'In congue. Etiam justo. Etiam pretium iaculis justo.', '£12.37', 'Broom - Corn', 6);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (7, 'True Heart Susie', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', '£5.62', 'Tamarillo', 7);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (8, 'Second Chorus', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '£21.88', 'Oregano - Fresh', 8);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (9, 'O Último Mergulho', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', '£32.09', 'Dikon', 9);
insert into menu_item (id, course, description, price, ingredients, subsidiary_restaurant_id) values (10, 'It Came from Hollywood', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '£30.68', 'Pasta - Tortellini, Fresh', 10);

COMMIT;